server:
  port: 8001

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

short-link:
  default-protocol: http
  # 短链接不存在时的跳转页面，为空则默认返回404错误
  not-found-redirect-url: /404.html
