server:
  port: 8001

spring:
  application:
    name: shortlink-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 
  jpa:
    database: mysql
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.xmon.shortlink.project.dao.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
